### ISSUE TITLE
All ops compiled successfully, but "No OpKernel was registered to support Op 'FarthestPointSample"

### ISSUE THREAD

**Issue by DustinReagan** [dgriffiths3/pointconv-tensorflow2#2]
It appears that all the custom ops were successfully compiled, however op 'FarthestPointSample' is missing?

Any ideas?
```
(tf) drreagan@ubuntupc:~/code/pointconv-tensorflow2$ tf_ops/compile_ops.sh 
Compiling GPU Ops...
Interpolate op compiled.
Grouping op compiled.
Sampling op compiled.
All ops compiled successfully.
(tf) drreagan@ubuntupc:~/code/pointconv-tensorflow2$ python train_scannet.py 
Model: "point_conv_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
point_conv_sa (PointConvSA)  multiple                  5440      
_________________________________________________________________
point_conv_sa_1 (PointConvSA multiple                  20800     
_________________________________________________________________
point_conv_sa_2 (PointConvSA multiple                  74240     
_________________________________________________________________
point_conv_sa_3 (PointConvSA multiple                  279424    
_________________________________________________________________
point_conv_fp (PointConvFP)  multiple                  409728    
_________________________________________________________________
point_conv_fp_1 (PointConvFP multiple                  106624    
_________________________________________________________________
point_conv_fp_2 (PointConvFP multiple                  49280     
_________________________________________________________________
point_conv_fp_3 (PointConvFP multiple                  36992     
_________________________________________________________________
dense (Dense)                multiple                  16512     
_________________________________________________________________
dropout (Dropout)            multiple                  0         
_________________________________________________________________
dense_1 (Dense)              multiple                  2709      
=================================================================
Total params: 1,001,749
Trainable params: 1,001,749
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/100
Traceback (most recent call last):
  File "train_scannet.py", line 100, in <module>
    train()
  File "train_scannet.py", line 78, in train
    model.fit(
  File "/home/drreagan/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/drreagan/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/drreagan/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/drreagan/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/drreagan/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/drreagan/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1661, in _filtered_call
    return self._call_flat(
  File "/home/drreagan/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/drreagan/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 593, in call
    outputs = execute.execute(
  File "/home/drreagan/miniconda3/envs/tf/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FarthestPointSample' used by {{node point_conv_sa/FarthestPointSample}} with these attrs: [npoint=1024]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'

	 [[point_conv_sa/FarthestPointSample]] [Op:__inference_train_function_6143]
```

**Comment by DustinReagan** [comment]
It was an issue with my ubuntu nvidia drivers...they weren't installed correctly, so tensorflow was defaulting to cpu mode and the cuda ops were not available.
